import { Hono } from 'hono';
import { getOrCreateHouseholdUser } from '../db/household.js';
import { getEbayAccessToken } from '../ebay/access-token.js';
import { loadOAuthConfig } from '../ebay/oauth.js';
import { addFixedPriceItem } from '../ebay/trading/add-fixed-price-item.js';
import type { AddItemResult } from '../ebay/trading/parsers.js';
import type { ListingPayload } from '../ebay/trading/xml.js';

export const listingsPublishRoute = new Hono();

// M1 hardcoded payload — used by POST /api/listings/publish to prove
// the OAuth + Trading API + sealing pipeline works end-to-end against
// eBay sandbox. M2+ will replace this with form-driven fields.
//
// Title gets a timestamp so each test publish is identifiable in the
// sandbox seller's listings page (eBay's title cap is 80 chars).
function buildHardcodedPayload(): ListingPayload {
  const stamp = new Date()
    .toISOString()
    .replace(/[-:.TZ]/g, '')
    .slice(0, 14);
  const title = `M1 test listing ${stamp} (DO NOT BUY)`;
  return {
    title: title.slice(0, 80),
    description:
      'Auto-generated by Brownrigg Ebay Listing Tool for sandbox integration testing. This listing is not a real product. Do not buy.',
    // 175673 = "Cell Phones & Smartphones > Apple iPhone" — a known
    // leaf category. The first M1 publish attempt used 11116 which is
    // a branch (parent) category; eBay rejected with errorCode 87
    // "Invalid category — not a leaf category". If 175673 surfaces
    // required item-aspects errors (Brand, Model, Storage), we'll
    // either add ItemSpecifics here or pick a less aspect-heavy leaf.
    categoryId: '175673',
    conditionId: 1000,
    startPrice: { value: 9.99, currency: 'USD' },
    postalCode: '95125',
    quantity: 1,
    shippingService: 'USPSPriority',
    shippingCost: { value: 5.0, currency: 'USD' },
    returnAcceptedDays: 30,
  };
}

function buildListingUrl(itemId: string, env: 'sandbox' | 'production'): string {
  const host = env === 'sandbox' ? 'www.sandbox.ebay.com' : 'www.ebay.com';
  return `https://${host}/itm/${itemId}`;
}

listingsPublishRoute.post('/', async (c) => {
  let config;
  try {
    config = loadOAuthConfig();
  } catch (e) {
    return c.json({ error: (e as Error).message }, 503);
  }

  let user;
  try {
    user = await getOrCreateHouseholdUser();
  } catch (e) {
    return c.json({ error: `failed to load household user: ${(e as Error).message}` }, 500);
  }

  let accessToken;
  try {
    accessToken = await getEbayAccessToken(user.id);
  } catch {
    // No ebay_auth row, or refresh failed — user needs to (re)connect.
    return c.json(
      {
        error: 'eBay not connected — visit /api/auth/ebay/login to authorize.',
      },
      401,
    );
  }

  const payload = buildHardcodedPayload();

  let result: AddItemResult;
  try {
    result = await addFixedPriceItem(payload, accessToken);
  } catch (e) {
    return c.json({ error: (e as Error).message }, 502);
  }

  switch (result.ack) {
    case 'Success':
    case 'Warning':
      return c.json({
        ack: result.ack,
        itemId: result.itemId,
        listingUrl: buildListingUrl(result.itemId, config.env),
        ...(result.startTime !== undefined ? { startTime: result.startTime } : {}),
        ...(result.endTime !== undefined ? { endTime: result.endTime } : {}),
        ...(result.warnings ? { warnings: result.warnings } : {}),
        payload: { title: payload.title },
      });
    case 'Failure':
    case 'PartialFailure':
      return c.json({ ack: result.ack, errors: result.errors }, 502);
  }
});
