import { Hono } from 'hono';
import { ListingDraftSchema, type ListingDraft } from '@ebay/shared';
import { getOrCreateHouseholdUser } from '../db/household.js';
import { getEbayAccessToken } from '../ebay/access-token.js';
import { loadOAuthConfig } from '../ebay/oauth.js';
import { addFixedPriceItem } from '../ebay/trading/add-fixed-price-item.js';
import type { AddItemResult } from '../ebay/trading/parsers.js';
import type { ListingPayload } from '../ebay/trading/xml.js';

export const listingsPublishRoute = new Hono();

// Map a validated form draft to the Trading API XML builder's payload
// type. Currently these are structurally identical — every ListingDraft
// is a valid ListingPayload because the schema is narrower (USD only,
// shipping-service enum). If they diverge later (e.g., to carry policy
// IDs or apply eBay-specific transforms), the divergence happens here
// rather than in the schema or the XML builder.
function draftToPayload(draft: ListingDraft): ListingPayload {
  return {
    title: draft.title,
    description: draft.description,
    categoryId: draft.categoryId,
    conditionId: draft.conditionId,
    startPrice: draft.startPrice,
    postalCode: draft.postalCode,
    quantity: draft.quantity,
    shippingService: draft.shippingService,
    shippingCost: draft.shippingCost,
    returnAcceptedDays: draft.returnAcceptedDays,
    ...(draft.pictureUrls !== undefined ? { pictureUrls: draft.pictureUrls } : {}),
    ...(draft.dispatchTimeMaxDays !== undefined
      ? { dispatchTimeMaxDays: draft.dispatchTimeMaxDays }
      : {}),
    ...(draft.listingDuration !== undefined ? { listingDuration: draft.listingDuration } : {}),
  };
}

// M1-style hardcoded payload — used when POST /api/listings/publish
// is called with no body (the curl smoke-test path). M2 forms send a
// real body and skip this entirely.
//
// Title gets a timestamp so each test publish is identifiable in the
// sandbox seller's listings page (eBay's title cap is 80 chars).
function buildHardcodedPayload(): ListingPayload {
  const stamp = new Date()
    .toISOString()
    .replace(/[-:.TZ]/g, '')
    .slice(0, 14);
  const title = `M1 test listing ${stamp} (DO NOT BUY)`;
  return {
    title: title.slice(0, 80),
    description:
      'Auto-generated by Brownrigg Ebay Listing Tool for sandbox integration testing. This listing is not a real product. Do not buy.',
    // 88433 = "Specialty Services > Other Specialty Services" — a
    // documented leaf category that's been stable in eBay's tree for
    // years. Earlier attempts with 11116 and 175673 both failed with
    // errorCode 87 "not a leaf category" — eBay's taxonomy has shifted
    // since those were leaves in older sample code. If this also
    // fails we'll add a GetSuggestedCategories helper rather than
    // continue guessing.
    categoryId: '88433',
    conditionId: 1000,
    startPrice: { value: 9.99, currency: 'USD' },
    postalCode: '95125',
    quantity: 1,
    shippingService: 'USPSPriority',
    shippingCost: { value: 5.0, currency: 'USD' },
    returnAcceptedDays: 30,
  };
}

function buildListingUrl(itemId: string, env: 'sandbox' | 'production'): string {
  const host = env === 'sandbox' ? 'www.sandbox.ebay.com' : 'www.ebay.com';
  return `https://${host}/itm/${itemId}`;
}

listingsPublishRoute.post('/', async (c) => {
  let config;
  try {
    config = loadOAuthConfig();
  } catch (e) {
    return c.json({ error: (e as Error).message }, 503);
  }

  let user;
  try {
    user = await getOrCreateHouseholdUser();
  } catch (e) {
    return c.json({ error: `failed to load household user: ${(e as Error).message}` }, 500);
  }

  let accessToken;
  try {
    accessToken = await getEbayAccessToken(user.id);
  } catch {
    // No ebay_auth row, or refresh failed — user needs to (re)connect.
    return c.json(
      {
        error: 'eBay not connected — visit /api/auth/ebay/login to authorize.',
      },
      401,
    );
  }

  // Decide the payload: parse a JSON body if present (M2 form path),
  // fall through to the hardcoded smoke-test payload if absent (M1
  // curl path — still useful for one-shot verification after a deploy).
  const raw: unknown = await c.req.json().catch(() => null);
  let payload: ListingPayload;
  if (raw === null || raw === undefined) {
    payload = buildHardcodedPayload();
  } else {
    const parsed = ListingDraftSchema.safeParse(raw);
    if (!parsed.success) {
      return c.json({ error: 'invalid body', issues: parsed.error.issues }, 400);
    }
    payload = draftToPayload(parsed.data);
  }

  let result: AddItemResult;
  try {
    result = await addFixedPriceItem(payload, accessToken);
  } catch (e) {
    return c.json({ error: (e as Error).message }, 502);
  }

  switch (result.ack) {
    case 'Success':
    case 'Warning':
      return c.json({
        ack: result.ack,
        itemId: result.itemId,
        listingUrl: buildListingUrl(result.itemId, config.env),
        ...(result.startTime !== undefined ? { startTime: result.startTime } : {}),
        ...(result.endTime !== undefined ? { endTime: result.endTime } : {}),
        ...(result.warnings ? { warnings: result.warnings } : {}),
        payload: { title: payload.title },
      });
    case 'Failure':
    case 'PartialFailure':
      return c.json({ ack: result.ack, errors: result.errors }, 502);
  }
});
